# Generated by Django 3.0.5 on 2020-04-27 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payed', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('acceptance_status', models.CharField(choices=[('Pen', 'در انتظار تایید'), ('Acc', 'تایید شده'), ('Rej', 'رد شده')], default='Pen', max_length=200, verbose_name='وضعیت تایید')),
                ('receipt', models.ImageField(upload_to='receipts', verbose_name='عکس فیش\u200cواریزی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cost', models.IntegerField(default=0, verbose_name='هزینه پرداختی')),
            ],
            options={
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='رشته')),
                ('university', models.CharField(max_length=100, verbose_name='دانشگاه')),
                ('guidance_master_full_name', models.CharField(max_length=100, verbose_name='استاد راهنما')),
                ('guidance_master_email', models.EmailField(max_length=200, verbose_name='ایمیل استاد راهنما')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'پروفایل',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درخواست')),
                ('date_expired', models.DateField(editable=False, null=True, verbose_name='تاریخ سررسید')),
                ('date_expired_admin_only', models.DateField(editable=False, null=True, verbose_name='تاریخ سررسید بعد از تایید')),
                ('os', models.CharField(choices=[('Win', 'Windows'), ('Lin', 'Linux')], max_length=50, verbose_name='سیستم عامل')),
                ('app_name', models.CharField(max_length=250, verbose_name='نام برنامه')),
                ('cpu', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='پردازنده')),
                ('ram', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='رم')),
                ('disk', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='دیسک')),
                ('days', models.IntegerField(default=0, verbose_name='تعداد روزها')),
                ('show_cost', models.IntegerField(default=0, verbose_name='هزینه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('user_description', models.TextField(blank=True, verbose_name='توضیحات کاربر')),
                ('serial_number', models.CharField(editable=False, max_length=16, unique=True, verbose_name='شماره سریال')),
                ('acceptance_status', models.CharField(choices=[('Pen', 'در انتظار تایید'), ('Paying', 'در انتظار پرداخت'), ('Acc', 'تایید شده'), ('Rej', 'رد شده'), ('Exting', 'در انتظار تمدید'), ('Caning', 'در انتظار لغو')], default='Pen', max_length=200, verbose_name='وضعیت تایید')),
                ('renewal_status', models.CharField(choices=[('Exp', 'منقضی'), ('Ok', 'نرمال'), ('Sus', 'تعلیق شده'), ('Can', 'لغو شده')], default='Ok', max_length=200, verbose_name='وضعیت سرویس')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Payment', verbose_name='پرداخت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'درخواست سرویس',
            },
        ),
        migrations.CreateModel(
            name='ExtendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0, verbose_name='تعداد روزها')),
                ('date_expired_admin_only', models.DateField(editable=False, null=True, verbose_name='تاریخ سررسید بعد از تایید')),
                ('receipt', models.ImageField(upload_to='receipts', verbose_name='عکس فیش\u200cواریزی')),
                ('show_cost', models.IntegerField(default=0, verbose_name='هزینه')),
                ('acceptance_status', models.CharField(choices=[('Pen', 'در انتظار تایید'), ('Acc', 'تایید شده'), ('Rej', 'رد شده')], default='Pen', max_length=200, verbose_name='وضعیت تایید')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Request', verbose_name='سرویس')),
            ],
            options={
                'verbose_name_plural': 'درخواست های تمدید',
            },
        ),
        migrations.CreateModel(
            name='CancelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_status', models.CharField(choices=[('Pen', 'در انتظار تایید'), ('Acc', 'تایید شده'), ('Rej', 'رد شده')], default='Pen', max_length=200, verbose_name='وضعیت تایید')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Request', verbose_name='سرویس')),
            ],
            options={
                'verbose_name_plural': 'درخواست های لغو',
            },
        ),
    ]
