# Generated by Django 3.0.5 on 2020-04-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_delete_extendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0, verbose_name='تعداد روزها')),
                ('date_expired_admin_only', models.DateField(editable=False, null=True, verbose_name='تاریخ سررسید بعد از تایید')),
                ('receipt', models.ImageField(upload_to='receipts', verbose_name='عکس فیش\u200cواریزی')),
                ('show_cost', models.IntegerField(default=0, verbose_name='هزینه')),
                ('acceptance_status', models.CharField(choices=[('Pen', 'در انتظار تایید'), ('Acc', 'تایید شده'), ('Rej', 'رد شده')], default='Pen', max_length=200, verbose_name='وضعیت تایید')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Request', verbose_name='سرویس')),
            ],
            options={
                'verbose_name_plural': 'درخواست های تمدید',
            },
        ),
    ]
