# Generated by Django 3.0.5 on 2020-04-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200407_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_expired',
            field=models.DateTimeField(editable=False, null=True, verbose_name=''),
        ),
    ]
