# Generated by Django 3.0.5 on 2020-04-07 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_request_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 18, 34, 21, 793042)),
        ),
    ]
