# Generated by Django 3.0.5 on 2020-04-07 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200407_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_expired',
            field=models.DateField(editable=False, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_requested',
            field=models.DateField(default=datetime.date(2020, 4, 7)),
        ),
    ]
