# Generated by Django 3.0.5 on 2020-04-07 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200407_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_requested',
            field=models.DateField(default=datetime.date(2020, 4, 7)),
        ),
    ]
