# Generated by Django 3.0.5 on 2020-04-09 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0012_auto_20200407_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(max_length=100, verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guidance_master_email',
            field=models.EmailField(max_length=200, verbose_name='ایمیل استاد راهنما'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guidance_master_full_name',
            field=models.CharField(max_length=100, verbose_name='استاد راهنما'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(max_length=100, verbose_name='دانشگاه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='request',
            name='acceptance_status',
            field=models.CharField(choices=[('Pen', 'در انتظار تایید'), ('Acc', 'تایید شده'), ('Rej', 'رد شده')], default=('Pen', 'در انتظار تایید'), max_length=20, verbose_name='وضعیت تایید'),
        ),
        migrations.AlterField(
            model_name='request',
            name='app_name',
            field=models.CharField(max_length=250, verbose_name='نام برنامه'),
        ),
        migrations.AlterField(
            model_name='request',
            name='cpu',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='پردازنده'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_expired',
            field=models.DateField(editable=False, null=True, verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='request',
            name='days',
            field=models.IntegerField(default=0, verbose_name='تعداد روزها'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='request',
            name='disk',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='دیسک'),
        ),
        migrations.AlterField(
            model_name='request',
            name='os',
            field=models.CharField(choices=[('Win', 'Windows'), ('Lin', 'Linux')], max_length=50, verbose_name='سیستم عامل'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ram',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='رم'),
        ),
        migrations.AlterField(
            model_name='request',
            name='renewal_status',
            field=models.CharField(choices=[('Exp', 'منقضی'), ('Ok', 'نرمال'), ('Sus', 'تعلیق شده'), ('Can', 'لغو شده')], default=('Ok', 'نرمال'), max_length=20, verbose_name='وضعیت سرویس'),
        ),
        migrations.AlterField(
            model_name='request',
            name='serial_number',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='شماره سریال'),
        ),
        migrations.AlterField(
            model_name='request',
            name='show_cost',
            field=models.IntegerField(default=0, verbose_name='هزینه'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Profile', verbose_name='کاربر'),
        ),
    ]
