# Generated by Django 3.0.5 on 2020-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20200410_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='acceptance_status',
            field=models.CharField(choices=[('Pen', 'در انتظار تایید'), ('Acc', 'تایید شده'), ('Rej', 'رد شده')], default='Pen', max_length=200, verbose_name='وضعیت تایید'),
        ),
        migrations.AlterField(
            model_name='request',
            name='renewal_status',
            field=models.CharField(choices=[('Exp', 'منقضی'), ('Ok', 'نرمال'), ('Sus', 'تعلیق شده'), ('Can', 'لغو شده')], default='Ok', max_length=200, verbose_name='وضعیت سرویس'),
        ),
    ]
