# Generated by Django 3.0.5 on 2020-04-11 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200410_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'درخواست'},
        ),
        migrations.AlterField(
            model_name='request',
            name='date_requested',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درخواست'),
        ),
    ]
