# Generated by Django 3.0.5 on 2020-04-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200411_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendrequest',
            name='date_expired',
        ),
        migrations.CreateModel(
            name='CancelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_status', models.CharField(choices=[('Pen', 'در انتظار تایید'), ('Acc', 'تایید شده'), ('Rej', 'رد شده')], default='Pen', max_length=200, verbose_name='وضعیت تایید')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Request', verbose_name='سرویس')),
            ],
            options={
                'verbose_name_plural': 'درخواست های لغو',
            },
        ),
    ]
