# Generated by Django 3.0.5 on 2020-04-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20200421_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='receipt',
            field=models.ImageField(default=None, upload_to='receipts', verbose_name='عکس فیش\u200cواریزی'),
            preserve_default=False,
        ),
    ]
