# Generated by Django 3.0.5 on 2020-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_request_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendrequest',
            name='receipt',
            field=models.ImageField(default=None, upload_to='receipts', verbose_name='عکس فیش\u200cواریزی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendrequest',
            name='show_cost',
            field=models.IntegerField(default=0, verbose_name='هزینه'),
        ),
    ]
