# Generated by Django 3.0.5 on 2020-04-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20200422_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_expired_admin_only',
            field=models.DateField(editable=False, null=True, verbose_name='تاریخ سررسید بعد از تایید'),
        ),
    ]
