# Generated by Django 3.0.5 on 2020-04-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_request_date_expired_admin_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendrequest',
            name='date_expired_admin_only',
            field=models.DateField(editable=False, null=True, verbose_name='تاریخ سررسید بعد از تایید'),
        ),
    ]
