# Generated by Django 3.0.5 on 2020-04-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_extendrequest_date_expired_admin_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payed', models.DateTimeField(auto_now_add=True)),
                ('acceptance_status', models.CharField(choices=[('Pen', 'در انتظار تایید'), ('Acc', 'تایید شده'), ('Rej', 'رد شده')], default='Pen', max_length=200, verbose_name='وضعیت تایید')),
                ('receipt', models.ImageField(upload_to='receipts', verbose_name='عکس فیش\u200cواریزی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cost', models.IntegerField(default=0, verbose_name='هزینه پرداختی')),
            ],
            options={
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
        migrations.RemoveField(
            model_name='request',
            name='receipt',
        ),
        migrations.AddField(
            model_name='request',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Payment', verbose_name='پرداخت'),
        ),
    ]
