# Generated by Django 3.0.5 on 2020-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20200426_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='acceptance_status',
            field=models.CharField(choices=[('Pen', 'در انتظار تایید'), ('Paying', 'در انتظار پرداخت'), ('Acc', 'تایید شده'), ('Rej', 'رد شده'), ('Exting', 'در انتظار تمدید'), ('Caning', 'در انتظار لغو')], default='Pen', max_length=200, verbose_name='وضعیت تایید'),
        ),
    ]
